language: node_js
node_js:
    - lts/*
script:
    - "npm run build"
    - "npm run lint"
    - "npm run c"
    - "curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov"